### ISSUE TITLE
Determine a way to safely optimize images from certain sources only

### ISSUE THREAD

**Issue by alberto56** [dcycle/thumbor-example#1]
Context
-----

In order to have fast-loading sites, we need images to have a small footprint, for example around 100kb.

We also want site editors to be able to upload images which are of any weight, for example 5mb, without worrying about optimizing the images.

Idealy, the CMS we use should be able to optimize images for different contexts.

For example, in Drupal this is often done using the [image styles](https://www.drupal.org/docs/core-modules-and-themes/core-modules/image-module/working-with-images) module in core, which means that:

* A site builder can define an image style of medium which is maximum 600 px wide with a jpg quality of 70% (for example).
* A content editor inserts an image of 5Mb with a width of 4000px.
* The image style module will automatically create a version of the image which is 600px wide and around 100kb to be dislayed.

What about non-Drupal sites?
-----

According to [Use image CDNs to optimize images, by Jeremy Wagner et al., 2019-08-14, on web.dev](https://web.dev/articles/image-cdns), we can use image CDNs to optimize images.

> Thumbor is the most popular self-managed image CDN.

There is a link to the article [How to install the Thumbor image CDN, by Katie Hempenius, 2019-08-14, on web.dev](https://web.dev/articles/install-thumbor).

A search for "thumbor docker" shows several options for using Docker files to host Thumbor.

Your tasks
-----

* Accept the invitation to the https://github.com/dcycle/thumbor-example repo.
* Make a local clone of the repo
* Run ./scripts/deploy.sh

At this point you will be able to go to your website at http://0.0.0.0:8706

Confirm you can see the unoptimized image on http://0.0.0.0:8706/large.html

Confirm you can see the optimized image at http://0.0.0.0:8706/optimized.html

The optimized image is:

> http://0.0.0.0:8705/unsafe/500x/webserver/large-image.jpg

* 500x means 500 pixels wide
* webserver is the hostname of the HTTPD service from within the network. This means that within Thumbor, http://0.0.0.0:8706 will not resolve to anything; instead you need to access the webserver through http://webserver because it is the name of the httpd service in docker-compose.yml.

Make sure Thumbor will not accept traffic from unauthorized sources
-----

Right now Thumbor can accept any traffic from any source.

For example, you can go to:

    http://0.0.0.0:8705/unsafe/x100/i.imgur.com/iRcAbA9.png

and you will see a very small image of a cat, 100 pixels high.

We need to tell Thumbor to only accept traffic from authorized sources, in this case "http://webserver" only.

**Comment by suresh-kumara-gist** [comment]
http://webserver/ is getting redirected to https://webserver/  . https://webserver/ is doesn't exist.

**Comment by alberto56** [comment]
That's normal. Here is how it works:

    ----- DOCKER -------------------    (your
    |                              |     computer)
    |   http://image_optimization  |
    |   - image_optimization -     |
    |   |                    |     | <= http://0.0.0.0:8705
    |   |                    |     |
    |   ----------------------     |
    |                              |
    |   http://webserver           |
    |   ---- webserver -------     |
    |   |                    |     | <= http://0.0.0.0:8706
    |   |                    |     |
    |   ----------------------     |
    |                              |
    --------------------------------

So http://webserver is unknown to your local computer, it is only accessible from within the docker network (so, from within the image_optimization container, http://webserver is visible, but from your computer it is not). From your computer, http://0.0.0.0:8705 and http://0.0.0.0:8706 are visible, but those same URLs are unknown from within the docker containers.

Try this:

```
\$ curl -I http://webserver
curl: (6) Could not resolve host: webserver
\$ # that is normal
zsh: command not found: #
\$ docker compose exec image_optimization /bin/bash -c 'curl -I http://webserver'
HTTP/1.1 200 OK
Date: Sat, 15 Jun 2024 20:54:47 GMT
Server: Apache/2.4.59 (Unix)
Last-Modified: Thu, 13 Jun 2024 19:55:33 GMT
ETag: "1ca-61acae1c2115e"
Accept-Ranges: bytes
Content-Length: 458
Content-Type: text/html
```

This shows that you need to be on a docker container within the docker network for http://webserver to work.

> http://webserver/ is getting redirected to https://webserver/

I don't think there is any redirection, but maybe your browser is trying to redirect in case it work (it will not).

**Comment by suresh-kumara-gist** [comment]
https://github.com/MinimalCompact/thumbor/blob/master/thumbor/conf/thumbor.conf.tpl 

in image_optimization container ./app/thumbor.conf we need to modify below values and verify result

      - ALLOW_UNSAFE_URL=True  # Allow Thumbor to manipulate URLs
      - ALLOWED_SOURCES = ['http://webserver']  # Specify the allowed source
